# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "66d05de3eb0f7d9c5da000b653621d9b"
name = "sitemap-generator"
handle = "sitemap-generator-5"
application_url = "https://varieties-tabs-hazardous-districts.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://varieties-tabs-hazardous-districts.trycloudflare.com/auth/callback",
  "https://varieties-tabs-hazardous-districts.trycloudflare.com/auth/shopify/callback",
  "https://varieties-tabs-hazardous-districts.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
